# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web-cv"

  # Use a Debian box compatible with the libvirt provider
  config.vm.box = "generic/alpine318"
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configure the libvirt (KVM) provider
  config.vm.provider :libvirt do |libvirt|
    # Allocate 1 GB of RAM (value is in MB)
    libvirt.memory = 1024

    # Allocate 1 virtual CPUs
    libvirt.cpus = 1

    # Set the primary disk size to 10 GB
    # This overrides the default size from the box.
    libvirt.machine_virtual_size = 10
  end
end
